// AUTO-GENERATED by scripts/seo-bot/generate-pages.mjs — do not edit.
declare module '@/data/programmatic/manifest.json' {
  export interface ProgrammaticManifestEntry {
    slug: string;
    path: string;
    category: 'salary' | 'hourly' | 'mortgage' | 'auto-loan' | 'growth';
    title: string;
    description: string;
    batch: number;
    published: boolean;
    dataFile: string;
  }
  const manifest: { pages: ProgrammaticManifestEntry[] };
  export default manifest;
}
