/**
 * generate-pages.mjs — programmatic SEO page generator for Fin Tools Lab.
 *
 * Computes every page payload deterministically (no Date.now, no randomness)
 * and writes:
 *   src/data/programmatic/manifest.json          — consumed by generateSitemap.cjs,
 *                                                  seo-bot/lib.mjs, release-batch.mjs
 *   src/data/programmatic/manifest.d.ts          — ambient types so the React app
 *                                                  can static-import manifest.json
 *   src/data/programmatic/<category>/<slug>.json — full page payloads
 *
 * Batching: batch 1 = first ~35 pages interleaved across categories
 * (published: true), batches 2–5 = the rest (published: false); the scheduled
 * bot releases them via scripts/seo-bot/release-batch.mjs.
 *
 * Usage:
 *   node scripts/seo-bot/generate-pages.mjs [--publish-batches=1,2]
 *     --publish-batches  comma list of batches to mark published (default: 1)
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { buildSalaryPages } from './page-configs/salary.mjs';
import { buildHourlyPages } from './page-configs/hourly.mjs';
import { buildMortgagePages } from './page-configs/mortgage.mjs';
import { buildAutoPages } from './page-configs/auto-loan.mjs';
import { buildGrowthPages } from './page-configs/growth.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const OUT_DIR = path.join(ROOT, 'src', 'data', 'programmatic');

const BATCH_1_SIZE = 35;
const LATER_BATCHES = 4; // batches 2–5

const publishArg = process.argv.find((a) => a.startsWith('--publish-batches='));
const publishBatches = new Set(
  (publishArg ? publishArg.split('=')[1] : '1')
    .split(',')
    .map((s) => parseInt(s.trim(), 10))
    .filter((n) => Number.isFinite(n))
);

/* ---------- 1. Build all pages ---------- */
const byCategory = {
  salary: buildSalaryPages(),
  hourly: buildHourlyPages(),
  mortgage: buildMortgagePages(),
  'auto-loan': buildAutoPages(),
  growth: buildGrowthPages(),
};

// Within each category: spec-core values first, then extensions, ascending.
for (const list of Object.values(byCategory)) {
  list.sort((a, b) => (Number(b.core) - Number(a.core)) || (a.sortKey - b.sortKey));
}

/* ---------- 2. Interleave categories round-robin ---------- */
const order = ['salary', 'hourly', 'mortgage', 'auto-loan', 'growth'];
const queues = order.map((c) => [...byCategory[c]]);
const interleaved = [];
while (queues.some((q) => q.length)) {
  for (const q of queues) {
    if (q.length) interleaved.push(q.shift());
  }
}

/* ---------- 3. Assign batches ---------- */
const total = interleaved.length;
const rest = total - BATCH_1_SIZE;
const base = Math.floor(rest / LATER_BATCHES);
const extra = rest % LATER_BATCHES; // first `extra` later batches get one more
const batchSizes = [BATCH_1_SIZE];
for (let i = 0; i < LATER_BATCHES; i++) batchSizes.push(base + (i < extra ? 1 : 0));

let cursor = 0;
const batched = batchSizes.flatMap((size, i) => {
  const chunk = interleaved.slice(cursor, cursor + size);
  cursor += size;
  return chunk.map((page) => ({ ...page, batch: i + 1 }));
});

/* ---------- 4. Write output ---------- */
fs.rmSync(OUT_DIR, { recursive: true, force: true });
fs.mkdirSync(OUT_DIR, { recursive: true });

const manifestPages = [];
for (const page of batched) {
  const dir = path.join(OUT_DIR, page.category);
  fs.mkdirSync(dir, { recursive: true });
  const dataFile = `src/data/programmatic/${page.category}/${page.slug}.json`;
  const published = publishBatches.has(page.batch);

  const payload = {
    slug: page.slug,
    path: page.path,
    category: page.category,
    title: page.title,
    metaDescription: page.metaDescription,
    ...page.payload,
  };
  fs.writeFileSync(
    path.join(dir, `${page.slug}.json`),
    JSON.stringify(payload, null, 2) + '\n',
    'utf-8'
  );

  manifestPages.push({
    slug: page.slug,
    path: page.path,
    category: page.category,
    title: page.title,
    description: page.metaDescription,
    batch: page.batch,
    published,
    dataFile,
  });
}

fs.writeFileSync(
  path.join(OUT_DIR, 'manifest.json'),
  JSON.stringify({ pages: manifestPages }, null, 2) + '\n',
  'utf-8'
);

// Ambient module declaration so the SPA can `import manifest from
// '@/data/programmatic/manifest.json'` without resolveJsonModule.
fs.writeFileSync(
  path.join(OUT_DIR, 'manifest.d.ts'),
  `// AUTO-GENERATED by scripts/seo-bot/generate-pages.mjs — do not edit.
declare module '@/data/programmatic/manifest.json' {
  export interface ProgrammaticManifestEntry {
    slug: string;
    path: string;
    category: 'salary' | 'hourly' | 'mortgage' | 'auto-loan' | 'growth';
    title: string;
    description: string;
    batch: number;
    published: boolean;
    dataFile: string;
  }
  const manifest: { pages: ProgrammaticManifestEntry[] };
  export default manifest;
}
`,
  'utf-8'
);

/* ---------- 5. Report ---------- */
const counts = {};
for (const p of manifestPages) counts[p.category] = (counts[p.category] || 0) + 1;
console.log(`Generated ${manifestPages.length} programmatic pages`);
for (const [cat, n] of Object.entries(counts)) console.log(`  ${cat.padEnd(10)} ${n}`);
console.log('Batches:');
for (let b = 1; b <= batchSizes.length; b++) {
  const inBatch = manifestPages.filter((p) => p.batch === b);
  const pub = inBatch.every((p) => p.published) ? 'published' : 'unpublished';
  const perCat = order
    .map((c) => `${c}:${inBatch.filter((p) => p.category === c).length}`)
    .join(' ');
  console.log(`  batch ${b}: ${inBatch.length} pages (${pub}) — ${perCat}`);
}
console.log(`Output: ${OUT_DIR}`);
